/*
 * @Author: Jacket-mzl
 * @Date: 2024-05-16 11:01:07
 * @LastEditors: Jacket-mzl
 * @LastEditTime: 2024-05-23 22:56:15
 * @Description:
 */
import type { Metadata } from "next";
import { Web3Provider } from "@/context/Web3";
import { WALLETCONNECT_CONFIG } from "@/utils/web3";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";
import { NotificationProvider } from "@/context/Notifications";
import "@/assets/globals.css";
import { Layout } from "@/components/Layout";
import { PropsWithChildren } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: PropsWithChildren) {
  const initialState = cookieToInitialState(
    WALLETCONNECT_CONFIG,
    headers().get("cookie")
  );
  console.log("RootLayout", props);
  return (
    <html lang="en">
      <head>
        <link rel="icon" />
      </head>
      <body>
        <Web3Provider initialState={initialState}>
          <NotificationProvider>
            <Layout>{props.children}</Layout>
          </NotificationProvider>
        </Web3Provider>
      </body>
    </html>
  );
}
